-- Create enum type for appointment status
CREATE TYPE public.appointment_status AS ENUM
    ('pending', 'confirmed', 'completed', 'cancelled');

ALTER TYPE public.appointment_status
    OWNER TO cse340_database;

-- Create appointment table
CREATE TABLE IF NOT EXISTS public.appointment
(
    appointment_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_id integer NOT NULL,
    inv_id integer NOT NULL,
    appointment_date date NOT NULL,
    appointment_time time NOT NULL,
    appointment_status appointment_status NOT NULL DEFAULT 'pending'::appointment_status,
    notes text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT appointment_pkey PRIMARY KEY (appointment_id),
    CONSTRAINT fk_appointment_account FOREIGN KEY (account_id)
        REFERENCES public.account (account_id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_appointment_inventory FOREIGN KEY (inv_id)
        REFERENCES public.inventory (inv_id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

